name: det
description: Suckless finance management app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.0.6
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.4
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/illustrations/
